#!/usr/bin/env python
import sys
import os
import git

# This hook is called with the following parameters:
# arg1 -- Name of the remote to which the push is being done
# arg2 -- URL to which the push is being done

remote = sys.argv[1]
# print(remote)

repo = git.Repo('.')
assert not repo.bare

if remote[:11] == "mirror_repo":
    sys.exit(0)
elif remote == "origin":
    # push to mirror repository when pushing to other destinations
    print("Pre-push hook pushing to mirrors")
    for remoteName in repo.remotes:
        if str(remoteName) != "origin":
            print("Pushing to: " + str(remoteName))
            os.system("git push --mirror --quiet " + str(remoteName))
    print("Push to mirrors completed")
    sys.exit(0)
else:
    sys.exit(0)
