#!/usr/bin/env python
import sys
import os

# This hook is called with the following parameters:
# arg1 -- Name of the remote to which the push is being done
# arg2 -- URL to which the push is being done

remote = sys.argv[1]
# print(remote)

if remote == "mirror_repo":
    sys.exit(0)
else:
    # push to mirror repository when pushing to other destinations
    print("pre-push hook pushing to mirror")
    os.system("git push --mirror --quiet mirror_repo")
    print("push to mirror completed")
    sys.exit(0)
